const axios = require('axios');
const FormData = require('form-data');

async function testPhase3Backend() {
    const API = 'http://localhost:5000/api';



    console.log('\n--- 2. Testing Expanded Preferences Evaluation ---');
    const dummyImage = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64');
    
    const consumerForm = new FormData();
    consumerForm.append('images', dummyImage, { filename: 'front.png', contentType: 'image/png' });
    consumerForm.append('images', dummyImage, { filename: 'back.png', contentType: 'image/png' });
    consumerForm.append('preferences', JSON.stringify({
        vegetarian: true,
        peanuts: true,
        diabetic_friendly_low_sugar: true,
        no_artificial_colors_flavors: true
    }));

    const consumerScanRes = await axios.post(`${API}/consumer/scan`, consumerForm, {
        headers: consumerForm.getHeaders()
    });
    console.log('Consumer Multi-Photo Scan:', consumerScanRes.data.status, '| Photos processed:', consumerScanRes.data.photoCount);
    console.log('Preference Results:', Object.keys(consumerScanRes.data.preferences?.details || {}));

    console.log('\n--- 3. Testing Officer Multi-Photo Scan with saveToRepository ---');
    const signupRes = await axios.post(`${API}/auth/signup`, {
        name: 'Inspector Meera Sen',
        email: `officer_p3_${Date.now()}@metrology.gov.in`,
        password: 'Password123'
    });
    const token = signupRes.data.token;

    const officerForm = new FormData();
    officerForm.append('images', dummyImage, { filename: 'label_front.png', contentType: 'image/png' });
    officerForm.append('images', dummyImage, { filename: 'label_back.png', contentType: 'image/png' });

    officerForm.append('saveToRepository', 'true');
    officerForm.append('productName', 'Multi-Pack Cookies 200g');

    const officerScanRes = await axios.post(`${API}/officer/scan`, officerForm, {
        headers: {
            ...officerForm.getHeaders(),
            Authorization: `Bearer ${token}`
        }
    });
    console.log('Officer Scan Status:', officerScanRes.data.status, '| Overall:', officerScanRes.data.overallStatus);
    console.log('Evidence images uploaded:', officerScanRes.data.savedInspection?.evidenceImages?.length);

    console.log('\n--- 4. Testing Compact PDF Generation ---');
    const pdfRes = await axios.post(`${API}/officer/report/pdf`, {
        scanTimestamp: new Date().toISOString(),
        productName: 'Multi-Pack Cookies 200g',
        overallStatus: 'PASS',
        extractedFields: {
            productName: 'Multi-Pack Cookies',
            mrp: { value: 60, inclusiveOfTaxes: true },
            netQuantity: { value: 200, unit: 'g' },
            photoCount: 2
        },
        findings: [
            { ruleCode: 'PCR-01', field: 'mrp', status: 'PASS', reason: 'MRP printed clearly' },
            { ruleCode: 'PCR-02', field: 'netQuantity', status: 'PASS', reason: 'Net quantity compliant' }
        ],
        evidenceImages: officerScanRes.data.savedInspection?.evidenceImages || []
    }, { 
        responseType: 'arraybuffer',
        headers: { Authorization: `Bearer ${token}` }
    });
    console.log('PDF Generated Bytes:', pdfRes.data.length);

    console.log('\n✅ ALL PHASE 3 BACKEND TESTS PASSED SUCCESSFULLY!');
}

testPhase3Backend().catch(err => {
    console.error('Phase 3 Test Error:', err.response?.data || err.message);
});
